from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, Float, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.database import Base


def _new_uuid() -> str:
    return str(uuid.uuid4())


class IntakeTemplate(Base):
    """
    Stores the definition of each agent type's intake form.

    A template describes which fields are required, which are optional,
    what clarification questions to ask, and any agent-specific config.
    """

    __tablename__ = "intake_templates"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_new_uuid)
    agent_type: Mapped[str] = mapped_column(String, unique=True, nullable=False, index=True)
    display_name: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    required_fields: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    optional_fields: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    clarification_map: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Maps field names to clarification questions when those fields are missing.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    runs: Mapped[list[AgentRun]] = relationship("AgentRun", back_populates="template")


class AgentRun(Base):
    """
    Tracks a single end-to-end agent run, from intake through archiving.
    """

    __tablename__ = "agent_runs"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_new_uuid)
    agent_type: Mapped[str] = mapped_column(String, nullable=False, index=True)
    template_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("intake_templates.id"), nullable=True
    )
    status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="pending",
        comment=(
            "One of: pending, running, needs_clarification, validated, pending_approval, "
            "approved, rejected, archived, error."
        ),
    )
    intake_data: Mapped[dict] = mapped_column(
        JSON, nullable=False, default=dict, comment="Raw intake payload submitted by the user."
    )
    normalized_data: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, comment="Cleaned/normalized version of intake_data."
    )
    missing_fields: Mapped[list] = mapped_column(
        JSON, nullable=False, default=list, comment="Fields found missing during validation."
    )
    clarification_questions: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="Clarification questions generated for missing fields.",
    )
    analysis_summary: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="Future high-level analysis summary."
    )
    score: Mapped[float | None] = mapped_column(
        Float, nullable=True, comment="Future opportunity score 0-10."
    )
    raw_llm_output: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, comment="Future full structured output from analysis."
    )
    reviewer_note: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="Note left by the human reviewer on approve/reject."
    )
    error_message: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="Error detail if the run encountered an exception."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    template: Mapped[IntakeTemplate | None] = relationship("IntakeTemplate", back_populates="runs")
    action_drafts: Mapped[list[ActionDraft]] = relationship(
        "ActionDraft", back_populates="run", cascade="all, delete-orphan"
    )


class ActionDraft(Base):
    """
    Stores a single action draft generated by the draft_action node.

    Multiple drafts can be produced for a single run (e.g. a short reply
    and a full proposal).
    """

    __tablename__ = "action_drafts"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=_new_uuid)
    run_id: Mapped[str] = mapped_column(
        String, ForeignKey("agent_runs.id"), nullable=False, index=True
    )
    action_type: Mapped[str] = mapped_column(
        String, nullable=False, comment="Category of action, e.g. 'reply', 'proposal', 'pass'."
    )
    title: Mapped[str] = mapped_column(String, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    is_approved: Mapped[bool | None] = mapped_column(
        nullable=True, comment="Set when the human reviewer approves this specific draft."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    run: Mapped[AgentRun] = relationship("AgentRun", back_populates="action_drafts")
